[package]
name = "day5"
version = "0.1.0"
authors = ["4cschneider <jeremiah.schneider@4com.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
